const sampleListings = [
  {
    title: "Desert King",
    description: "Beautiful place in the heart of the desert with amazing views and relaxing atmosphere.",
    image: "https://images.unsplash.com/photo-1606788075761-1b53d66f1423?auto=format&fit=crop&w=800&q=60",
    price: 2000,
    location: "Desert Oasis",
    country: "United States",
  },
  {
    title: "Beachside Bungalow",
    description: "Wake up to the sound of waves and the ocean breeze in this charming bungalow.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Miami Beach",
    country: "United States",
  },
  {
    title: "Mountain Cabin",
    description: "Cozy cabin nestled in the mountains, perfect for a peaceful retreat or hiking adventure.",
    image: "https://images.unsplash.com/photo-1519974719765-e6559eac2575?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Modern City Apartment",
    description: "Stylish apartment in the heart of downtown with all modern amenities and city views.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "New York",
    country: "United States",
  },
  {
    title: "Tropical Treehouse",
    description: "Live amongst the trees in this beautiful treehouse surrounded by lush jungle.",
    image: "https://images.unsplash.com/photo-1587502536263-9298c38b7b31?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Hilo",
    country: "Hawaii",
  },
  {
    title: "Lakefront Lodge",
    description: "Enjoy calm mornings and beautiful sunsets by the lake in this cozy lodge.",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=60",
    price: 2100,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Rustic Barn Stay",
    description: "Experience country life with a modern twist in this renovated rustic barn.",
    image: "https://images.unsplash.com/photo-1559599238-095e469fae62?auto=format&fit=crop&w=800&q=60",
    price: 1700,
    location: "Nashville",
    country: "United States",
  },
  {
    title: "Ski Chalet",
    description: "Hit the slopes and then relax by the fire in this alpine ski chalet.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
    price: 2800,
    location: "Vail",
    country: "United States",
  },
  {
    title: "Historic Castle",
    description: "Live like royalty in this beautifully restored historic castle with breathtaking views.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Edinburgh",
    country: "Scotland",
  },
  {
    title: "Eco Bamboo Villa",
    description: "Sustainable living at its finest in this open-air bamboo villa surrounded by nature.",
    image: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=60",
    price: 2300,
    location: "Bali",
    country: "Indonesia",
  },
];

module.exports = { data: sampleListings };
